### PR TITLE
refactor: centralize helpers and fix macOS  sed  compatibility

### LINKED ISSUE #157: Fix macOS `sed -i` Compatibility and Centralize Script Helpers
We are currently encountering an issue where `sed -i` commands fail on macOS because BSD `sed` requires an explicit extension argument. This causes scripts to print their content instead of modifying files in place.

Additionally, several of our scripts contain duplicated and similar logic. To improve maintainability and reduce duplication, this common logic should be centralized into a shared utility module.

### PR DESCRIPTION
**Pull request by Awambeng**
This PR improves maintainability, ensures cross-platform compatibility, and reduces code duplication, making future updates safer and easier.

**Key Changes:**
- **Fixed macOS Compatibility**: Introduced a portable `sed_inplace` helper to handle differences between **GNU** and **BSD** `sed` in-place editing.
- **Centralized Utilities**: Created scripts/utils.sh and scripts/utils.ps1 to house shared logic for logging, path detection, and privilege handling.
- **Global Refactoring**: Standardized all 14 installation and uninstallation scripts to use these shared utilities.
- **Visual Consistency**: Aligned logging formats and color schemes across shell and PowerShell environments for a uniform user experience.

Closes #157

### CODE REVIEW

File: scripts/install.sh [hunk 1]
```diff
@@ -1,81 +1,17 @@
...
 
-# Set shell options
-if [ -n "$BASH_VERSION" ]; then
-    set -euo pipefail
-else
-    set -eu
-fi
+# Source shared utilities
+# shellcheck source=scripts/utils.sh
+. "$(dirname "$0")/utils.sh"
```
Comment (t-desmond) [inline scripts/install.sh]: Image

Image

Sourcing with dirname only works with files on the same filesystem. A possible fix is downloading the utils scripts before sourcing

Comment (Awambeng) [reply scripts/install.sh]: Thank you. I’ve updated the scripts to ensure the utility file is downloaded before being sourced.

File: scripts/deps.sh [hunk 2]
```diff
@@ -1,36 +1,16 @@
...
-error_message() {
-    log ERROR "$*"
-}
-
-success_message() {
-    log INFO "$*"
-}
+# Source shared utilities
+: "${WAZUH_AGENT_REPO_REF:=main}"
+curl -sSL "https://raw.githubusercontent.com/ADORSYS-GIS/wazuh-agent/${WAZUH_AGENT_REPO_REF}/scripts/utils.sh" -o utils.sh
```
Comment (MarantosGeorge) [inline scripts/deps.sh]: Please add some error handling to the download of the script.

File: scripts/install.sh [hunk 3]
```diff
@@ -1,81 +1,18 @@
...
 
-# Set shell options
-if [ -n "$BASH_VERSION" ]; then
-    set -euo pipefail
-else
-    set -eu
-fi
+# Source shared utilities
+: "${WAZUH_AGENT_REPO_REF:=main}"
+curl -sSL "https://raw.githubusercontent.com/ADORSYS-GIS/wazuh-agent/${WAZUH_AGENT_REPO_REF}/scripts/utils.sh" -o utils.sh
```
Comment (MarantosGeorge) [inline scripts/install.sh]: Please add some error handling to the download of the script.

File: scripts/setup-agent.sh [hunk 4]
```diff
@@ -1,11 +1,9 @@
...
 
-# Check if we're running in bash; if not, adjust behavior
-if [ -n "$BASH_VERSION" ]; then
-    set -euo pipefail
-else
-    set -eu
-fi
+# Source shared utilities
+: "${WAZUH_AGENT_REPO_REF:=main}"
+curl -sSL "https://raw.githubusercontent.com/ADORSYS-GIS/wazuh-agent/${WAZUH_AGENT_REPO_REF}/scripts/utils.sh" -o utils.sh
```
Comment (MarantosGeorge) [inline scripts/setup-agent.sh]: Please add some error handling to the download of the script.

**Review by MarantosGeorge — CHANGES_REQUESTED** [review]

**Comment by Awambeng** [comment]
@MarantosGeorge Thank you for the review!
I've added error handling for downloading the shared utility script. Could you please take another look?

File: scripts/install.ps1 [hunk 5]
```diff
@@ -1,12 +1,17 @@
...
+    exit 1
+}
+. ./utils.ps1
+
 $WAZUH_MANAGER = if ($env:WAZUH_MANAGER) { $env:WAZUH_MANAGER } else { "wazuh.example.com" }
 $WAZUH_AGENT_VERSION = if ($env:WAZUH_AGENT_VERSION) { $env:WAZUH_AGENT_VERSION } else { "4.14.2-1" }
 
-
-# Global variables
-$OSSEC_PATH = "C:\Program Files (x86)\ossec-agent\"
```
Comment (MarantosGeorge) [inline scripts/install.ps1:6]: Are these variables to be added to the utils.ps1? 

Since line 19 uses these variables

File: scripts/setup-agent.ps1 [hunk 6]
```diff
@@ -12,8 +23,6 @@ $LOG_LEVEL = if ($env:LOG_LEVEL) { $env:LOG_LEVEL } else { "INFO" }
 $APP_NAME = if ($env:APP_NAME) { $env:APP_NAME } else { "wazuh-cert-oauth2-client" }
 $WAZUH_MANAGER = if ($env:WAZUH_MANAGER) { $env:WAZUH_MANAGER } else { "wazuh.example.com" }
 $WAZUH_AGENT_VERSION = if ($env:WAZUH_AGENT_VERSION) { $env:WAZUH_AGENT_VERSION } else { "4.14.2-1" }
-$OSSEC_PATH = "C:\Program Files (x86)\ossec-agent\"
```
Comment (MarantosGeorge) [inline scripts/setup-agent.ps1:15]: Again for these variables are they meant to be added to utils.ps1?
Since they are used furthen in the script on line 27

**Review by MarantosGeorge — CHANGES_REQUESTED** [review]

File: scripts/install.ps1 (hunk 5 above)
Comment (Awambeng) [reply scripts/install.ps1:6]: I moved the variable into the shared utility to avoid repetition and ensure a single source of truth (see: https://github.com/ADORSYS-GIS/wazuh-agent/pull/158/changes#diff-8438fcdb1b6525ad98aeb8f73b952048bfc5be43c27c8f6b602dba4c6f4b4fee)
This makes the variable available to all sub-scripts, since the shared utility is sourced beforehand.

File: scripts/setup-agent.ps1 (hunk 6 above)
Comment (Awambeng) [reply scripts/setup-agent.ps1:15]: same response applies here.

File: scripts/install.ps1 (hunk 5 above)
Comment (MarantosGeorge) [reply scripts/install.ps1:6]: Okay Great!

**Review by MarantosGeorge — APPROVED** [review]
LGTM!
